In [3]:
import numpy as np

array_ceros = np.zeros(10)
print(array_ceros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
import numpy as np

array_1_20 = np.arange(1, 21)
print(array_1_20)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
import numpy as np


pares_2_50 = np.arange(2, 51, 2)
print(pares_2_50)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [6]:
import numpy as np


matriz_4x4 = np.random.rand(4, 4)
print(matriz_4x4)

[[0.99183571 0.89783231 0.78302758 0.97886024]
 [0.2053813  0.77978828 0.61171337 0.35989871]
 [0.06646842 0.52049102 0.21222931 0.37749081]
 [0.02896116 0.11135504 0.09067812 0.88195906]]


In [7]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

suma = a + b
print(suma)

[5 7 9]


In [8]:
import numpy as np

matriz1 = np.random.randint(1, 11, size=(3, 3))
matriz2 = np.random.randint(1, 11, size=(3, 3))

producto = np.dot(matriz1, matriz2)

print("Matriz 1:\n", matriz1)
print("Matriz 2:\n", matriz2)
print("Producto:\n", producto)

Matriz 1:
 [[ 7 10  3]
 [ 6  3  2]
 [ 5  3  9]]
Matriz 2:
 [[ 6  4 10]
 [ 7  9  3]
 [10 10  3]]
Producto:
 [[142 148 109]
 [ 77  71  75]
 [141 137  86]]


In [10]:
import numpy as np
array_random = np.random.randint(1, 101, 15)

maximo = array_random.max()
minimo = array_random.min()
promedio = array_random.mean()

print("Array:", array_random)
print("Máximo:", maximo)
print("Mínimo:", minimo)
print("Promedio:", promedio)

Array: [52 18 41 78 49 39 27 55 15  6 44 32 45  4 79]
Máximo: 79
Mínimo: 4
Promedio: 38.93333333333333


In [11]:
import numpy as np
matriz_5x5 = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(matriz_5x5)

print("Matriz:\n", matriz_5x5)
print("Diagonal:", diagonal)


Matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal: [ 1  7 13 19 25]


In [13]:
import numpy as np
matriz = np.random.randint(1, 21, size=(5, 5))

suma_filas = matriz.sum(axis=1)
suma_columnas = matriz.sum(axis=0)

print("Matriz:\n", matriz)
print("Suma por filas:", suma_filas)
print("Suma por columnas:", suma_columnas)


Matriz:
 [[ 5  9  9 20  9]
 [ 9  8 11  1  2]
 [ 4  5 19 17 10]
 [ 1 14  3  1  4]
 [ 1 12  4 18  6]]
Suma por filas: [52 31 55 23 41]
Suma por columnas: [20 48 46 57 31]
